package net.milanaleksic.mcs.db;

// Generated 07.11.2007. 23.32.08 by Hibernate Tools 3.2.0.b9

import java.math.BigDecimal;
import java.util.*;


/**
 * Film generated by hbm2java
 */
public class Film implements java.io.Serializable {

	private int idfilm;
	private Zanr zanr;
	private String nazivfilma;
	private String prevodnazivafilma;
	private int godina;
	private String komentar;
	private BigDecimal imdbrejting;
	private Set<Medij> medijs = new HashSet<Medij>(0);

	public Film() {
	}

	public Film(int idfilm, Zanr zanr, String nazivfilma, String prevodnazivafilma, int godina, BigDecimal imdbrejting) {
		this.idfilm = idfilm;
		this.zanr = zanr;
		this.nazivfilma = nazivfilma;
		this.prevodnazivafilma = prevodnazivafilma;
		this.godina = godina;
		this.imdbrejting = imdbrejting;
	}

	public Film(int idfilm, Zanr zanr, String nazivfilma, String prevodnazivafilma, int godina, String komentar, BigDecimal imdbrejting,
			Set<Medij> medijs) {
		this.idfilm = idfilm;
		this.zanr = zanr;
		this.nazivfilma = nazivfilma;
		this.prevodnazivafilma = prevodnazivafilma;
		this.godina = godina;
		this.komentar = komentar;
		this.imdbrejting = imdbrejting;
		this.medijs = medijs;
	}

	public int getIdfilm() {
		return this.idfilm;
	}

	public void setIdfilm(int idfilm) {
		this.idfilm = idfilm;
	}

	public Zanr getZanr() {
		return this.zanr;
	}

	public void setZanr(Zanr zanr) {
		this.zanr = zanr;
	}

	public String getNazivfilma() {
		return this.nazivfilma;
	}

	public void setNazivfilma(String nazivfilma) {
		this.nazivfilma = nazivfilma;
	}

	public String getPrevodnazivafilma() {
		return this.prevodnazivafilma;
	}

	public void setPrevodnazivafilma(String prevodnazivafilma) {
		this.prevodnazivafilma = prevodnazivafilma;
	}

	public int getGodina() {
		return this.godina;
	}

	public void setGodina(int godina) {
		this.godina = godina;
	}

	public String getKomentar() {
		return this.komentar;
	}

	public void setKomentar(String komentar) {
		this.komentar = komentar;
	}

	public BigDecimal getImdbrejting() {
		return this.imdbrejting;
	}

	public void setImdbrejting(BigDecimal imdbrejting) {
		this.imdbrejting = imdbrejting;
	}

	public Set<Medij> getMedijs() {
		return this.medijs;
	}

	public void setMedijs(Set<Medij> medijs) {
		this.medijs = medijs;
	}
	
	public String toString() {
		return getNazivfilma();
	}
	
	public void addMedij(Medij m) {
		medijs.add(m);
		m.getFilms().add(this);
	}
	
	public String getFilmLocation() {
		// priprema informacija za narednu obradu (polje "prisutan")
		int brojNeprisutnih = 0;
		for (Medij medij : getMedijs()) {
			if (!medij.getPozicija().equals("присутан"))
				brojNeprisutnih++;
		}
		
		// obrada polja "prisutan"
		String prisutan = null;
		if (brojNeprisutnih==0)
			prisutan = "присутан";
		else {
			StringBuffer buffer = new StringBuffer();
			for (Medij medij : getMedijs()) {
				buffer.append(medij.toString()+"-"+medij.getPozicija().toString()+"; ");
			}
			prisutan = buffer.substring(0,buffer.length()-2);
		}						
		for (Medij medij : getMedijs()) {
			if (!medij.getPozicija().equals("присутан"))
				prisutan = medij.getPozicija().toString();
		}
		return prisutan;
	}

}