package net.milanaleksic.mcs.domain;

// Generated 07.11.2007. 23.32.08 by Hibernate Tools 3.2.0.b9

import java.util.HashSet;
import java.util.Set;

/**
 * LogerAkcija generated by hbm2java
 */
public class LogerAkcija implements java.io.Serializable {

	private int idlogerakcija;
	private String naziv;
	private Set<Loger> logers = new HashSet<Loger>(0);

	public LogerAkcija() {
	}

	public LogerAkcija(int idlogerakcija, String naziv) {
		this.idlogerakcija = idlogerakcija;
		this.naziv = naziv;
	}

	public LogerAkcija(int idlogerakcija, String naziv, Set<Loger> logers) {
		this.idlogerakcija = idlogerakcija;
		this.naziv = naziv;
		this.logers = logers;
	}

	public int getIdlogerakcija() {
		return this.idlogerakcija;
	}

	public void setIdlogerakcija(int idlogerakcija) {
		this.idlogerakcija = idlogerakcija;
	}

	public String getNaziv() {
		return this.naziv;
	}

	public void setNaziv(String naziv) {
		this.naziv = naziv;
	}

	public Set<Loger> getLogers() {
		return this.logers;
	}

	public void setLogers(Set<Loger> logers) {
		this.logers = logers;
	}
	
	public String toString() {
		return getNaziv();
	}
	
	public void addLoger(Loger l) {
		logers.add(l);
		l.setLogerAkcija(this);
	}

}
